'use client'

import { FormEvent, useState } from 'react'
import { LibraryBig, Pencil, Plus, Search, Send, GraduationCap, ClipboardCheck, ListChecks, X, Trash2 } from 'lucide-react'
import { ProcessSelector } from '@/components/app/process-selector'
import { api } from '@/lib/api'
import { Procedure, procedureLabel } from '@/lib/requirements'
import { Alert, Empty, Field, fieldError, Loading, Panel, useAction, useAsync } from '@/components/app/ui'

type Template = {tipo_tramite:string|null;id:number;nombre:string;descripcion:string|null;obligatorio:boolean;activo:boolean}
type Career = {id:number;nombre:string;activa:boolean;facultad_id?:number;facultad?:string}
type Catalog = {carreras:Career[];facultades?:{id:number;nombre:string;activa:boolean}[];tramites:Procedure[]}

export function QuickRequirementAssignment({catalog,onAssigned}:{catalog:Catalog;onAssigned:()=>void}) {
 const library=useAsync(()=>api<{data:Template[]}>('/admin/requirement-templates').then(r=>r.data),[])
 const action=useAction();const save=useAction()
 const [faculty,setFaculty]=useState('');const [search,setSearch]=useState('');const [procedure,setProcedure]=useState('')
 const [careers,setCareers]=useState<number[]>([]);const [requirements,setRequirements]=useState<number[]>([])
 const [removing,setRemoving]=useState<Template|null>(null)
 const [editing,setEditing]=useState<Template|'new'|null>(null)
 const [form,setForm]=useState({nombre:'',descripcion:'',obligatorio:true,activo:true})
 const selectedProcess=catalog.tramites.find(t=>t.id===Number(procedure))?.tipo_tramite
 const visibleTemplates=library.data?.filter(t=>selectedProcess&&t.tipo_tramite===selectedProcess)??[]
 const pendingTemplates=library.data?.filter(t=>!t.tipo_tramite&&t.activo)??[]
 const activeTemplates=visibleTemplates.filter(t=>t.activo)
 const available=catalog.carreras.filter(c=>c.activa&&(!c.facultad_id||catalog.facultades?.find(f=>f.id===c.facultad_id)?.activa!==false))
 const visible=available.filter(c=>(!faculty||c.facultad_id===Number(faculty))&&`${c.nombre} ${c.facultad??''}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()))
 function edit(template:Template|'new'){setRemoving(null);setEditing(template);setForm(template==='new'?{nombre:'',descripcion:'',obligatorio:true,activo:true}:{...template,descripcion:template.descripcion??''});save.setError(null);save.setMessage('')}
 async function saveTemplate(event:FormEvent){event.preventDefault();const result=await save.run(()=>api(`/admin/requirement-templates${editing==='new'?'':`/${(editing as Template).id}`}`,{method:editing==='new'?'POST':'PUT',body:{...form,tipo_tramite:selectedProcess}}),'Biblioteca actualizada.');if(result){setEditing(null);library.reload()}}
 async function removeTemplate(){if(!removing)return;const id=removing.id;const result=await action.run(()=>api(`/admin/requirement-templates/${id}`,{method:'DELETE'}),'Requisito eliminado de la biblioteca. Las listas ya asignadas se conservan.');if(result){setRemoving(null);setRequirements(old=>old.filter(value=>value!==id));library.reload()}}
 async function prepareTemplates(){if(!selectedProcess)return;const result=await action.run(()=>api<{data:Template[]}>('/admin/requirement-templates/prepare',{method:'POST',body:{tipo_tramite:selectedProcess}}),'Precargados incorporados al proceso. Revisa los requisitos seleccionados antes de asignar.');if(result){await library.reload();setRequirements(result.data.map(t=>t.id))}}
 async function assign(event:FormEvent){event.preventDefault();const result=await action.run(()=>api<{data:{asignados:number;existentes:number}}>('/admin/requirement-templates/assign',{method:'POST',body:{carrera_ids:careers,template_ids:requirements.filter(id=>library.data?.some(t=>t.id===id&&t.activo)),tramite_proceso_id:Number(procedure)}}));if(result){action.setMessage(`${result.data.asignados} asignación(es) creada(s). ${result.data.existentes} ya existían y se conservaron. Los coordinadores pueden consultar los requisitos en sus carreras.`);onAssigned()}}
 return <Panel className="quick-requirement-assignment" title="Asignación rápida de requisitos">
  <div className="requirement-library-intro"><LibraryBig size={24}/><div><strong>Selecciona una vez y asigna a varias carreras</strong><p>Usa la biblioteca precargada. Cada carrera recibe su propia lista para que el coordinador pueda ajustarla.</p></div></div>
  <Alert error={library.error??action.error} message={action.message} inlineFields/>
  {removing&&<div className="confirm-banner" role="alert"><div><strong>¿Eliminar «{removing.nombre}» de la biblioteca?</strong><p>Dejará de estar disponible para nuevas asignaciones. Las carreras y solicitudes que ya lo tienen conservarán sus requisitos.</p></div><button type="button" className="btn btn-outline" disabled={action.busy} onClick={()=>setRemoving(null)}>Cancelar</button><button type="button" className="btn btn-danger" disabled={action.busy} onClick={removeTemplate}><Trash2 size={15}/>Eliminar de la biblioteca</button></div>}

  <form onSubmit={assign} className="requirement-assignment">
   <div className="form-grid management-form"><ProcessSelector procedures={catalog.tramites} value={procedure} onChange={value=>{setProcedure(value);setRequirements([]);setEditing(null);setRemoving(null)}} disabled={action.busy} error={fieldError(action.error,'tramite_proceso_id')}/></div>
   <div className="requirement-assignment-columns">
    <section><header><h4><GraduationCap size={19}/>2. Carreras de destino</h4><span>{careers.length} seleccionada(s)</span></header><Field label="Filtrar por facultad"><select value={faculty} onChange={e=>setFaculty(e.target.value)}><option value="">Todas las facultades</option>{catalog.facultades?.filter(f=>f.activa).map(f=><option key={f.id} value={f.id}>{f.nombre}</option>)}</select></Field><label className="search-box"><Search size={16}/><input aria-label="Buscar carreras para asignar requisitos" placeholder="Buscar carrera…" value={search} onChange={e=>setSearch(e.target.value)}/></label><button type="button" className="link-button assignment-select-button" onClick={()=>setCareers([...new Set([...careers,...visible.map(c=>c.id)])])}><ListChecks size={16}/>Seleccionar carreras visibles</button><div className="assignment-options">{visible.length?visible.map(c=><label className={careers.includes(c.id)?'is-selected':''} key={c.id}><input type="checkbox" checked={careers.includes(c.id)} onChange={e=>setCareers(e.target.checked?[...careers,c.id]:careers.filter(id=>id!==c.id))}/><span><strong>{c.nombre}</strong><small>{c.facultad??'Sin facultad'}</small></span></label>):<Empty>No hay carreras activas con este filtro.</Empty>}</div>{careers.length>0&&<button type="button" className="link-button assignment-clear-button" onClick={()=>setCareers([])}><X size={15}/>Limpiar selección de carreras</button>}<small className="field-error" role="alert">{fieldError(action.error,'carrera_ids')??fieldError(action.error,'carrera_ids.0')}</small><p className="field-hint">Las carreras seleccionadas se conservan al cambiar el filtro de facultad.</p></section>
    <section><header><h4><ClipboardCheck size={19}/>3. Requisitos de {selectedProcess==='homologacion'?'homologación':selectedProcess==='reconocimiento'?'reconocimiento':'este proceso'}</h4><span>{requirements.length} seleccionado(s)</span></header><div className="library-action-toolbar">{selectedProcess&&<button type="button" className="btn btn-outline" disabled={save.busy||action.busy} onClick={()=>edit('new')}><Plus size={16}/>Crear requisito</button>}<button type="button" className="link-button assignment-select-button" disabled={!activeTemplates.length||action.busy} onClick={()=>setRequirements(activeTemplates.map(t=>t.id))}><ListChecks size={16}/>Seleccionar todos ({activeTemplates.length})</button></div>
     {!selectedProcess?<p className="field-hint">Elige primero el proceso y su opción.</p>:!activeTemplates.length?<p className="field-hint">Este proceso todavía no tiene requisitos activos. Crea uno o incorpora los precargados disponibles abajo.</p>:<p className="field-hint">Marca únicamente los requisitos que corresponden a este proceso.</p>}
     <div className="assignment-options">{library.loading&&!library.data?<Loading/>:visibleTemplates.map(t=><div className={`assignment-template ${requirements.includes(t.id)&&t.activo?'is-selected':''} ${!t.activo?'is-inactive':''}`} key={t.id}><label><input type="checkbox" disabled={!t.activo||!t.tipo_tramite} checked={requirements.includes(t.id)&&t.activo} onChange={e=>setRequirements(e.target.checked?[...requirements,t.id]:requirements.filter(id=>id!==t.id))}/><span><strong>{t.nombre}</strong><small>{!t.tipo_tramite?'Pendiente de clasificar':!t.activo?'Inactivo':t.obligatorio?'Obligatorio':'Complementario'} · {t.descripcion}</small></span></label><button type="button" className="btn btn-ghost" title="Editar requisito precargado" aria-label={`Editar requisito precargado ${t.nombre}`} onClick={()=>edit(t)}><Pencil size={15}/></button><button type="button" className="btn btn-ghost danger-text" disabled={action.busy} aria-label={`Eliminar requisito precargado ${t.nombre}`} title="Eliminar de la biblioteca" onClick={()=>{setEditing(null);setRemoving(t)}}><Trash2 size={15}/></button></div>)}</div>{selectedProcess&&pendingTemplates.length>0&&<details className="library-pending"><summary>Precargados disponibles para incorporar ({pendingTemplates.length})</summary><p>Incorporarlos crea una copia en la biblioteca de {selectedProcess==='homologacion'?'homologación':'reconocimiento'}. Revisa cuáles corresponden; no se asignan a carreras todavía.</p><ul>{pendingTemplates.map(t=><li key={t.id}>{t.nombre}</li>)}</ul><button type="button" className="btn btn-outline" disabled={action.busy} onClick={prepareTemplates}><Plus size={15}/>Incorporar y seleccionar precargados</button></details>}
     <button type="button" className="link-button assignment-clear-button" onClick={()=>setRequirements([])}><X size={15}/>Limpiar selección de requisitos</button><small className="field-error" role="alert">{fieldError(action.error,'template_ids')??fieldError(action.error,'template_ids.0')}</small></section>
   </div>
   <div className="assignment-summary"><div><strong>4. Confirmar asignación · {careers.length} carrera(s) · {requirements.filter(id=>library.data?.some(t=>t.id===id&&t.activo)).length} requisito(s)</strong><p>Se asignarán a {catalog.tramites.find(t=>t.id===Number(procedure))?procedureLabel(catalog.tramites.find(t=>t.id===Number(procedure))!):'un trámite pendiente de seleccionar'}. Los requisitos existentes no se duplican ni se sobrescriben.</p>{careers.length>0&&<small>Carreras: {available.filter(c=>careers.includes(c.id)).map(c=>c.nombre).join(', ')}</small>}</div><button className="btn btn-primary" disabled={action.busy||!procedure||!careers.length||!requirements.some(id=>library.data?.some(t=>t.id===id&&t.activo))}><Send size={16}/>{action.busy?'Asignando…':'Asignar requisitos'}</button></div>
  </form>
  {editing&&<form className="form-grid management-form library-editor" onSubmit={saveTemplate}><strong>{editing==='new'?'Nuevo requisito precargado':'Editar requisito de la biblioteca'} · {selectedProcess==='homologacion'?'Homologación':'Reconocimiento'}</strong><Alert error={save.error} inlineFields/><Field label="Nombre" error={fieldError(save.error,'nombre')}><input autoFocus required maxLength={150} value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></Field><Field label="Indicaciones" error={fieldError(save.error,'descripcion')}><textarea maxLength={2000} value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})}/></Field><Field label="Tipo"><select value={form.obligatorio?'1':'0'} onChange={e=>setForm({...form,obligatorio:e.target.value==='1'})}><option value="1">Obligatorio</option><option value="0">Complementario</option></select></Field>{editing!=='new'&&<Field label="Disponibilidad"><select value={form.activo?'1':'0'} onChange={e=>setForm({...form,activo:e.target.value==='1'})}><option value="1">Activo</option><option value="0">Inactivo</option></select></Field>}<p className="field-hint">Editar la biblioteca modifica futuras asignaciones. Las listas ya asignadas conservan sus ajustes.</p><div className="form-actions"><button type="button" className="btn btn-outline" disabled={save.busy} onClick={()=>setEditing(null)}>Cancelar</button><button className="btn btn-primary" disabled={save.busy}>Guardar en biblioteca</button></div></form>}
 </Panel>
}
