'use client'
import { FormEvent, useState } from 'react'
import { GraduationCap, Pencil, Plus, Search, UserCheck, UserRoundX } from 'lucide-react'
import { api, Paginated } from '@/lib/api'
import { Alert, Empty, Field, Loading, PageHeader, Panel, Pager, useAction, useAsync } from '@/components/app/ui'
type Career={id:number;nombre:string;activa:boolean;modalidades:{id:number;nombre:string;activa:boolean}[]}
type Student={id:number;nombres_completos:string;tipo_identificacion:string;cedula:string;email:string;numero_celular:string;cuenta_activa:boolean;carreras?:{id:number;nombre:string;modalidad_id?:number}[]}
function StudentForm({student,careers,onDone,onCancel}:{student?:Student;careers:Career[];onDone:()=>void;onCancel:()=>void}) {
 const action=useAction()
 const [form,setForm]=useState({nombres_completos:student?.nombres_completos??'',tipo_identificacion:student?.tipo_identificacion??'cedula',cedula:student?.cedula??'',email:student?.email??'',numero_celular:student?.numero_celular??'',carrera_id:String(student?.carreras?.[0]?.id??''),modalidad_id:String(student?.carreras?.[0]?.modalidad_id??'')})
 const set=(key:keyof typeof form,value:string)=>setForm(old=>({...old,[key]:value}))
 async function submit(e:FormEvent){e.preventDefault();const result=await action.run(()=>api(`/coordinator/students${student?`/${student.id}`:''}`,{method:student?'PUT':'POST',body:{...form,cedula:form.cedula.trim().toUpperCase(),carrera_id:Number(form.carrera_id),modalidad_id:Number(form.modalidad_id)}}));if(result)onDone()}
 return <Panel title={student?'Editar estudiante':'Registrar estudiante'} actions={<button className="btn btn-ghost" disabled={action.busy} onClick={onCancel}>Cerrar</button>}><Alert error={action.error}/><form className="form-grid management-form" onSubmit={submit}>
 <Field label="Nombres completos"><input autoFocus required maxLength={255} value={form.nombres_completos} onChange={e=>set('nombres_completos',e.target.value)}/></Field>
 <Field label="Tipo de identificación"><select value={form.tipo_identificacion} onChange={e=>setForm({...form,tipo_identificacion:e.target.value,cedula:''})}><option value="cedula">Cédula ecuatoriana</option><option value="pasaporte">Pasaporte</option></select></Field>
 <Field label={form.tipo_identificacion==='cedula'?'Número de cédula':'Número de pasaporte'} hint={form.tipo_identificacion==='cedula'?'Exactamente 10 dígitos.':'Entre 5 y 20 letras o números.'}><input required inputMode={form.tipo_identificacion==='cedula'?'numeric':'text'} minLength={form.tipo_identificacion==='cedula'?10:5} maxLength={form.tipo_identificacion==='cedula'?10:20} pattern={form.tipo_identificacion==='cedula'?'[0-9]{10}':'[A-Za-z0-9]{5,20}'} value={form.cedula} onChange={e=>set('cedula',e.target.value.toUpperCase())}/></Field>
 <Field label="Correo electrónico"><input required type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="Celular"><input required minLength={7} maxLength={20} value={form.numero_celular} onChange={e=>set('numero_celular',e.target.value)}/></Field>
 <Field label="Carrera de destino en la UEB"><select required value={form.carrera_id} onChange={e=>setForm({...form,carrera_id:e.target.value,modalidad_id:''})}><option value="">Selecciona una carrera asignada</option>{careers.filter(c=>c.activa).map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select></Field>
 <Field label="Modalidad de destino"><select required value={form.modalidad_id} onChange={e=>set('modalidad_id',e.target.value)}><option value="">Selecciona una modalidad</option>{careers.find(c=>c.id===Number(form.carrera_id))?.modalidades.filter(m=>m.activa).map(m=><option key={m.id} value={m.id}>{m.nombre}</option>)}</select></Field>
 <p className="muted">La carrera de origen se registra en los antecedentes académicos. Las nuevas cuentas reciben una contraseña temporal por correo.</p>
 <div className="form-actions"><button type="button" className="btn btn-outline" disabled={action.busy} onClick={onCancel}>Cancelar</button><button className="btn btn-primary" disabled={action.busy}>{action.busy?'Guardando…':student?'Guardar cambios':'Crear estudiante'}</button></div></form></Panel>
}
export function CoordinatorStudents(){
 const [search,setSearch]=useState('');const [type,setType]=useState('');const [page,setPage]=useState(1)
 const [editing,setEditing]=useState<Student|'new'|null>(null);const [statusTarget,setStatusTarget]=useState<Student|null>(null)
 const students=useAsync(()=>api<Paginated<Student>>('/coordinator/students',{query:{search,tipo_identificacion:type,page,per_page:12}}),[search,type,page])
 const catalog=useAsync(()=>api<{data:{carreras:Career[]}}>('/coordinator/catalogo').then(r=>r.data),[])
 const action=useAction()
 async function editStudent(id:number){const r=await action.run(()=>api<{data:Student}>(`/coordinator/students/${id}`));if(r){setEditing(r.data);setStatusTarget(null)}}
 async function changeStatus(){if(!statusTarget)return;const result=await action.run(()=>api(`/coordinator/students/${statusTarget.id}/status`,{method:'PATCH',body:{cuenta_activa:!statusTarget.cuenta_activa}}),'Estado de cuenta actualizado.');if(result){setStatusTarget(null);students.reload()}}
 return <><PageHeader kicker="COORDINACIÓN ACADÉMICA" title="Estudiantes" subtitle="Registra estudiantes y asigna su carrera y modalidad de destino." actions={<button className="btn btn-primary" onClick={()=>{setEditing('new');setStatusTarget(null)}}><Plus size={16}/>Nuevo estudiante</button>}/>
 <div className="management-banner"><GraduationCap size={28}/><div><strong>Un expediente, un acompañamiento claro</strong><p>Administra los estudiantes de tus carreras. Su documentación se recibe y valida presencialmente.</p></div><span>{students.data?.meta.total??'—'} estudiantes</span></div>
 <Alert error={students.error??catalog.error??action.error} message={action.message}/>
 {editing&&catalog.data&&<StudentForm key={editing==='new'?'new':editing.id} student={editing==='new'?undefined:editing} careers={catalog.data.carreras} onDone={()=>{setEditing(null);students.reload();action.setMessage('Estudiante guardado correctamente.')}} onCancel={()=>setEditing(null)}/>}
 {statusTarget&&<div className="confirm-banner"><p>¿{statusTarget.cuenta_activa?'Desactivar':'Reactivar'} la cuenta de <strong>{statusTarget.nombres_completos}</strong>? Su historial se conservará.</p><button className="btn btn-outline" onClick={()=>setStatusTarget(null)}>Cancelar</button><button className="btn btn-primary" disabled={action.busy} onClick={changeStatus}>Confirmar</button></div>}
 <Panel><div className="management-toolbar"><label className="search-box"><Search size={17}/><input aria-label="Buscar estudiantes" placeholder="Nombre, identificación o correo…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label><select aria-label="Filtrar identificación" value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="">Todas las identificaciones</option><option value="cedula">Cédula</option><option value="pasaporte">Pasaporte</option></select></div>
 {students.loading&&!students.data?<Loading/>:!students.data?.data.length?<Empty>No se encontraron estudiantes. Puedes registrar uno nuevo o ajustar la búsqueda.</Empty>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Estudiante</th><th>Identificación</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{students.data.data.map(s=><tr key={s.id}><td><strong>{s.nombres_completos}</strong><small className="cell-description">{s.email}</small></td><td>{s.cedula}<small className="cell-description">{s.tipo_identificacion==='pasaporte'?'Pasaporte':'Cédula'}</small></td><td><span className={`status ${s.cuenta_activa?'approved':''}`}>{s.cuenta_activa?'Activo':'Inactivo'}</span></td><td><div className="row-actions"><button className="btn btn-ghost" disabled={action.busy} onClick={()=>editStudent(s.id)}><Pencil size={15}/>Editar</button><button className="btn btn-ghost" onClick={()=>setStatusTarget(s)}>{s.cuenta_activa?<UserRoundX size={15}/>:<UserCheck size={15}/>} {s.cuenta_activa?'Desactivar':'Reactivar'}</button></div></td></tr>)}</tbody></table></div>}
 {students.data&&<Pager meta={students.data.meta} onPage={setPage}/>}</Panel></>
}
